version: '3'
services:
  web:
    build: .
    container_name: php-apache-container-pr3
    volumes:
      - ./static:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db-container-pr3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./static/actions:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data:
